name: Publish

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libcurl4-openssl-dev libxslt-dev libxml2-dev # required to avoid SSL errors
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build site
        run: |
          JEKYLL_ENV=production bundle install
          JEKYLL_ENV=production bundle exec jekyll build --destination docs
          echo "blog.mothertongues.org" >> docs/CNAME
          bundle exec rake test
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
